/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      'localhost',
      'localhost:3000',
      'cdn.moralis.io',
      'etherscan.io',
      'res.cloudinary.com',
      'widget.onramper.com',
      'onramper.tech',
      'd33wubrfki0l68.cloudfront.net',
      'empressthemes.com',
      'creativesocialnft.io',
      'creativesocial.io',
      'chat.creativesocialnft.io',
      'creativesocialnft.com',
      'api.wallet.coinbase.com',
      'cms.creativesocialnft.com',
      'strapi-9l0s.onrender.com',
      'cdn.sanity.io',
      'csnft.sanity.studio',
      'ag7xdnxz.api.sanity.io',
      'avatars.githubusercontent.com',
      'platform-lookaside.fbsbx.com',
      'firebasestorage.googleapis.com',
      'googletagmanager.com',
      'avatars.githubusercontent.com',
      'firestore.googleapis.com',
      'facebook.com',
      'platform-lookaside.fbsbx.com',
      'etherscan.io',
      'media-exp1.licdn.com',
      'pbs.twimg.com',
      'googleusercontent.com',
      'lh3.googleusercontent.com',
      'api.lorem.space',
      'events-service.coinbase.com',
      'coinbase.com',
      'gateway.ipfscdn.io',
      'ipfs.creativesocialnft.io',
      'links.papareact.com',
      'avatars.dicebear.com'
    ],
  },
}
